---
- name: Ensure groups exist
  ansible.builtin.group:
    name: "{{ item }}"
    state: present
  with_items: "{{ custom_groups }}"

- name: Manage users
  ansible.builtin.user:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    shell: "{{ item.shell }}"
    groups: "{{ item.groups | join(',') }}"
    password: "{{ item.password | password_hash('sha512') }}"
    create_home: true
  with_items: "{{ users }}"

- name: Add SSH key for users
  ansible.builtin.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.ssh_key }}"
  loop: "{{ users }}"
  when: item.ssh_key is defined
